name: server-sdk
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 9 * * *'
  push:
    branches: [ main, 'feat/**' ]
    paths:
      - 'server-sdk/**'
      - '.github/workflows/server-sdk.yml'
  pull_request:
    branches: [ main, 'feat/**' ]
    paths:
      - 'server-sdk/**'
      - '.github/workflows/server-sdk.yml'

jobs:
  build-and-run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    permissions:
      id-token: write # Needed if using OIDC to get release secrets.

    defaults:
      run:
        working-directory: server-sdk/getting-started

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup dotnet build tools
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: 8.0

      - name: Restore dotnet dependencies
        shell: bash
        id: restore
        run: dotnet restore

      - name: Build
        shell: bash
        id: build
        run: dotnet build

      - uses: launchdarkly/gh-actions/actions/verify-hello-app@verify-hello-app-v2
        with:
          use_server_key: true
          role_arn: ${{ vars.AWS_ROLE_ARN }}
          command: cd server-sdk/getting-started && dotnet run --project HelloDotNet --framework net8.0
